name: Run Tests

on:
  push:
    branches: [ main, develop, staging ]
    paths:
      - 'src/**'
      - 'function_app/**'
      - 'package.json'
      - '.github/workflows/run-tests.yml'
  pull_request:
    branches: [ main, develop, staging ]
  workflow_dispatch:  # Allow manual triggering

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run test coverage
        run: npm run test:coverage

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: coverage/
          retention-days: 7

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r function_app/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          cd function_app
          python -m pytest --cov=. --cov-report=xml

      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: function_app/coverage.xml
          retention-days: 7

  integration-tests:
    name: Integration Tests
    needs: [frontend-tests, backend-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          npm ci
          python -m pip install --upgrade pip
          pip install -r function_app/requirements.txt
          pip install pytest

      - name: Start backend server
        run: |
          cd function_app
          # Start the Azure Functions runtime in the background
          func start &
          # Wait for the server to start
          sleep 10

      - name: Run integration tests
        run: |
          # Run integration tests that test the frontend and backend together
          # This is a placeholder for actual integration tests
          echo "Running integration tests..."
          # Example: npm run test:integration

      - name: Stop backend server
        run: |
          # Find and kill the Azure Functions process
          pkill -f "func start" || true 